# Generated by Django 4.2.9 on 2024-02-06 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='room',
            field=models.IntegerField(default=1, max_length=15),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='img',
            field=models.ImageField(default=None, upload_to=''),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='name',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
