# Generated by Django 4.2.9 on 2024-01-28 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('course', models.CharField(max_length=255, unique=True)),
                ('date_time', models.DateTimeField(unique=True)),
                ('attendance', models.DecimalField(decimal_places=0, max_digits=13)),
                ('room', models.DecimalField(decimal_places=0, max_digits=20)),
                ('payment', models.DecimalField(decimal_places=0, max_digits=12)),
                ('is_payment', models.BooleanField(default=False)),
                ('status', models.BooleanField(verbose_name=True)),
            ],
        ),
    ]
