# Generated by Django 4.2.9 on 2024-02-09 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_alter_student_attendance_alter_student_course_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='course_date',
            field=models.CharField(default=0, max_length=255),
        ),
    ]
