# Generated by Django 4.2.9 on 2024-01-25 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_myuser_date_joined_myuser_is_active_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='date_joined',
        ),
    ]
