# Generated by Django 4.2.9 on 2024-01-25 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_myuser_date_joined_myuser_groups_myuser_is_superuser_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='myuser',
            table=None,
        ),
    ]
