# Generated by Django 4.2.9 on 2024-01-25 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_alter_myuser_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='user_permissions',
        ),
    ]
