# Generated by Django 4.2.9 on 2024-01-25 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_remove_myuser_date_joined_remove_myuser_groups_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='date_joined',
            field=models.DateTimeField(default=None),
        ),
    ]
