# Generated by Django 4.2.9 on 2024-01-29 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_myuser_groups_myuser_is_superuser_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='is_staff',
        ),
    ]
